name: fuyu
description: "ğŸ‚ A self-hostable rest api server for Tenka."
version: 1.0.0

publish_to: none

environment:
    sdk: ">=2.15.0-226.0.dev <3.0.0"

dependencies:
    args: ^2.0.0
    dl: ^1.0.6
    path: ^1.8.1
    shelf: ^1.1.0
    shelf_router: ^1.0.0
    tenka:
        git:
            url: git://github.com/yukino-org/packages.git
            ref: dart_tenka
    utilx:
        git:
            url: git://github.com/yukino-org/packages.git
            ref: dart_utilx
    utilx_desktop:
        git:
            url: git://github.com/yukino-org/packages.git
            ref: dart_utilx_desktop

dev_dependencies:
    devx:
        git:
            url: git://github.com/yukino-org/packages.git
            ref: dart_devx
    test: ^1.15.0
